-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 15:14:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto_sorteio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_sorteio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_sorteio` ;
USE `projeto_sorteio` ;

-- -----------------------------------------------------
-- Table `projeto_sorteio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sorteio`.`usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `projeto_sorteio`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sorteio`.`sessao` (
  `id_sessao` BIGINT NOT NULL AUTO_INCREMENT,
  `id_usuario` BIGINT NOT NULL,
  `numero_minimo` INT NOT NULL,
  `numero_maximo` INT NOT NULL,
  PRIMARY KEY (`id_sessao`),
  INDEX `fk_sessao_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto_sorteio`.`usuario` (`id_usuario`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `projeto_sorteio`.`sorteio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_sorteio`.`sorteio` (
  `id_sorteio` BIGINT NOT NULL AUTO_INCREMENT,
  `id_sessao` BIGINT NOT NULL,
  `numero_sorteado` INT NOT NULL,
  PRIMARY KEY (`id_sorteio`),
  UNIQUE INDEX `uk_sessao_numero` (`id_sessao` ASC, `numero_sorteado` ASC) VISIBLE,
  INDEX `fk_sorteio_sessao` (`id_sessao` ASC) VISIBLE,
  CONSTRAINT `fk_sorteio_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `projeto_sorteio`.`sessao` (`id_sessao`)
    ON DELETE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
