spring.application.name=backend

# Conexao com o MySQL da VM db
spring.datasource.url=jdbc:mysql://10.20.30.3:3306/projeto_sorteio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=projeto
spring.datasource.password=projeto123

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do backend
server.port=8080